### PR TITLE
Go Code with Colors, Cleaner and a Bit Faster Code

### PR DESCRIPTION
**Pull request by gagliardetto**
Hi Alessio and Empatica team,

How are you? We met last Friday at `Codemotion`, and you got me interested in working with Empatica.

I researched a bit on Empatica, and what definitely convinced me was the talk Matteo Lai gave at `WIRED Health Summit` a few months ago.

I'm proposing a contribution to `csvparser`, and if you deem it proper, we can talk further about the "position of `Full-Stack Web Developer`", a.k.a. Your problem solver for everything web-related.

Cheers,

S.

### CODE REVIEW

**Comment by alecha** [comment]
Hi @gagliardetto , thanks for the contribution! I'll take a look this week!

For the Full Stack Dev role, did you already apply on our website? We're looking forward to receive you CV so we can talk about the position together. 

Thanks,
Alessio

**Comment by alecha** [comment]
Hi @gagliardetto, I've noticed that the code coverage went to 99% just because there is 2 lines of duplicate code 

`if err != nil {
		return nil, err
	}
`

that you can simply remove so the PR can be closed.

If I have to be honest the `SkipFirstLine` handling requires a couple of lines of code, what do you think if we put something like

`if parser.SkipFirstLine{
csvReader.Read()
}`

before the `for` loop so the first line will be discarded?

**Comment by gagliardetto** [comment]
Hi @alecha,

`if parser.SkipFirstLine{ csvReader.Read() }`

is great! It spares us from checking whether `parser.SkipFirstLine` is true in each iteration of the loop. Thanks for pointing out that waste of resources!

**Comment by alecha** [comment]
Thanks! PR closed!

**Pull request merged**
